name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@main

    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Set up Ruby
      uses: actions/setup-ruby@main
      with:
        ruby-version: '3.0'

    - name: Install RubyGems
      run: |
        gem install bundler -v "~>1"
        bundle install --jobs 4 --retry 3

    - name: Run tests
      run: bundle exec rspec spec/*